# Tentative NumPy Tutorial

http://scipy.github.io/old-wiki/pages/Tentative_NumPy_Tutorial

## The basics

In [1]:
from numpy import *

In [2]:
a = arange(15).reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [12]:
print(a.shape,"\n", 
      a.ndim,"\n",
     a.dtype.name,"\n",
     a.itemsize,"\n",
     a.size,"\n",
     type(a))

(3, 5) 
 2 
 int64 
 8 
 15 
 <class 'numpy.ndarray'>


In [13]:
b = array([6,7,8])
type(b)

numpy.ndarray

In [17]:
c = array([(1,2),(3,4)], dtype=complex)
c

array([[ 1.+0.j,  2.+0.j],
       [ 3.+0.j,  4.+0.j]])

In [22]:
random_array = ones((2,3))
random_array

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [29]:
x = linspace(0,2*pi,11)

In [30]:
f = sin(x)
f

array([  0.00000000e+00,   5.87785252e-01,   9.51056516e-01,
         9.51056516e-01,   5.87785252e-01,   1.22464680e-16,
        -5.87785252e-01,  -9.51056516e-01,  -9.51056516e-01,
        -5.87785252e-01,  -2.44929360e-16])