# Tentative NumPy Tutorial

http://scipy.github.io/old-wiki/pages/Tentative_NumPy_Tutorial

## The Basics

In [2]:
from numpy import *

In [3]:
a = arange(15).reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [4]:
print(a.shape,"\n", 
      a.ndim,"\n",
     a.dtype.name,"\n",
     a.itemsize,"\n",
     a.size,"\n",
     type(a))

(3, 5) 
 2 
 int32 
 4 
 15 
 <class 'numpy.ndarray'>


In [5]:
b = array([6,7,8])
type(b)

numpy.ndarray

In [6]:
c = array([(1,2),(3,4)], dtype=complex)
c

array([[ 1.+0.j,  2.+0.j],
       [ 3.+0.j,  4.+0.j]])

In [7]:
random_array = ones((2,3))
random_array

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [8]:
x = linspace(0,2*pi,11)

In [9]:
f = sin(x)
f

array([  0.00000000e+00,   5.87785252e-01,   9.51056516e-01,
         9.51056516e-01,   5.87785252e-01,   1.22464680e-16,
        -5.87785252e-01,  -9.51056516e-01,  -9.51056516e-01,
        -5.87785252e-01,  -2.44929360e-16])

In [10]:
a = array([[1,1],
          [0,1]])
b = array([[2,0],
          [3,4]])
print(dot(a,b),"\n\n",a*b)

[[5 4]
 [3 4]] 

 [[2 0]
 [0 4]]


In [11]:
b+=a
b

array([[3, 1],
       [3, 5]])

In [12]:
b.sum(axis=1)

array([4, 8])

In [13]:
sqrt(b)

array([[ 1.73205081,  1.        ],
       [ 1.73205081,  2.23606798]])

In [14]:
a = arange(10) **3
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [15]:
a[2:5]

array([ 8, 27, 64], dtype=int32)

In [16]:
a[:10:2] = -1
a

array([ -1,   1,  -1,  27,  -1, 125,  -1, 343,  -1, 729], dtype=int32)

In [17]:
a = a[::-1]
a

array([729,  -1, 343,  -1, 125,  -1,  27,  -1,   1,  -1], dtype=int32)

In [18]:
def f(x,y):
    return 10*x+y
b = fromfunction(f,(5,4),dtype=int)
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [19]:
b[1]

array([10, 11, 12, 13])

In [20]:
shape(b)

(5, 4)

In [21]:
b[1][1:3]

array([11, 12])

In [22]:
b[1:3, : ]

array([[10, 11, 12, 13],
       [20, 21, 22, 23]])

## Shape Manipulation

In [23]:
a

array([729,  -1, 343,  -1, 125,  -1,  27,  -1,   1,  -1], dtype=int32)